itea/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name="home/home.html"), name='home'),
    path('members/', include('members.urls', namespace='members')),
    path('balance/', include('balance.urls', namespace='balance')),
    path('notice/', include('notice.urls', namespace='notice')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from members.views import SignUp, UserListView, UserDetailView, UserBasicUpdateView, UserProfileUpdateView, \
    ActivateMemberRequest

app_name = "member"

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('list/', UserListView.as_view(), name='member-list'),
    path('details/<int:pk>/', UserDetailView.as_view(), name='member-details'),
    path('basic/<int:pk>/update', UserBasicUpdateView.as_view(), name='basic-update'),
    path('profile/<int:pk>/update', UserProfileUpdateView.as_view(), name='profile-update'),
    path('activate/', ActivateMemberRequest.as_view(), name='activate'),
]

notice/urls.py
from django.urls import path

from notice.views import NoticeCreate, NoticeListView, NoticeDetailView, \
    NoticeUpdateView, NoticeDeleteView, NoticeBoard

app_name = "notice"

urlpatterns = [
    path('list/', NoticeListView.as_view(), name='notice-list'),
    path('create/', NoticeCreate.as_view(), name='notice-create'),
    path('<int:pk>/', NoticeDetailView.as_view(), name='notice-details'),
    path('<int:pk>/update/', NoticeUpdateView.as_view(), name='notice-edit'),
    path('<int:pk>/delete/', NoticeDeleteView.as_view(), name='notice-delete'),
    path('board/', NoticeBoard.as_view(), name='notice-board'),
]

templates/home/about_itea.html
{% load static %}
<div class="content second-content">
    <div class="container-fluid">
        <div class="col-md-6">
            <div class="left-content">
                <h2>About ITEA DEMO WEB APP</h2>
                <ul>
                    <li> <h2 id="text">This web application will manage monthly financial transaction of every member of the organization</h2></li>
                    <li> <h2 id="text">This web application will manage expense transaction of the organization</h2></li>
                    <li> <h2 id="text">This web application will manage income transaction of the organization</h2></li>
                    <li> <h2 id="text">Transaction query by date and specific member</h2></li>
                    <li> <h2 id="text">Calculate Due months</h2></li>
                    <li> <h2 id="text">Total calculation of the members' balance, organizational expense and income</h2></li>
                    <li> <h2 id="text">Email Notification for every transaction</h2></li>
                    <li> <h2 id="text">And more.............!</h2></li>
                </ul>

          </div>
        </div>
        <div class="col-md-6">
            <div class="right-image">
              <img src="{% static 'img/about_image.jpg' %}" alt="">
          </div>
        </div>
    </div>
</div>

templates/home/about_us.html
{% load static%}

<div class="content third-content">
    <div class="container-fluid">
        <div class="col-md-12">
            <div class="row">
                <div class="first-section">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="left-content">
                                    <h2>I am Jr. Software Engineer</h2>
                                    <p>At present I am working as a Jr. Software Engineer at ME-SOLshare Ltd. (From September-2019)</p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="right-image">
                                    <img src="{% static 'img/first_service.jpg' %}" alt="first service">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="second-section">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="left-image">
                                    <img src="{% static 'img/second_service.jpg' %}" alt="second service">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="right-content">
                                    <h2>Academically I am a Textile Engineer from DUET</h2>
                                    <p>I have completed my graduation from DUET from Textile Engineering Department but my career is now going with Software Engineering field</p>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/home/dashboard.html
<div class="content fifth-content">
    <div class="container-fluid">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-12">
                  <fieldset>
                      <a href="{% url 'member:login' %}">
                          <button type="link" id="form-submit" class="btn login-button">Login</button>
                      </a>
                      <a href="{% url 'member:signup' %}">
                          <button type="link" id="form-submit" class="btn">Sign Up</button>
                      </a>
                  </fieldset>
                </div>
            </div>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>

templates/home/footer.html
<div class="content">
    <p>Copyright &copy; 2020 MSI Shafik . <a href="http://www.facebook.com/shafik.te/">On Facebook</a> - <a href="https://www.linkedin.com/in/shafikte/" target="_parent">On LinkedIn</a></p>
</div>

templates/home/home.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>ITEA-Ideal Textile Engineers' Association</title>
<!-- 
Moonlight Template 
http://www.templatemo.com/tm-512-moonlight
-->
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
{#        <link rel="apple-touch-icon" href="apple-touch-icon.png">#}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/fontAwesome.css' %}">
        <link rel="stylesheet" href="{% static 'css/light-box.css' %}">
        <link rel="stylesheet" href="{% static 'css/templatemo-main.css' %}">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">

        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    </head>

<body>
    
    <div class="sequence">
  
      <div class="seq-preloader">
        <svg width="39" height="16" viewBox="0 0 39 16" xmlns="http://www.w3.org/2000/svg" class="seq-preload-indicator"><g fill="#F96D38"><path class="seq-preload-circle seq-preload-circle-1" d="M3.999 12.012c2.209 0 3.999-1.791 3.999-3.999s-1.79-3.999-3.999-3.999-3.999 1.791-3.999 3.999 1.79 3.999 3.999 3.999z"/><path class="seq-preload-circle seq-preload-circle-2" d="M15.996 13.468c3.018 0 5.465-2.447 5.465-5.466 0-3.018-2.447-5.465-5.465-5.465-3.019 0-5.466 2.447-5.466 5.465 0 3.019 2.447 5.466 5.466 5.466z"/><path class="seq-preload-circle seq-preload-circle-3" d="M31.322 15.334c4.049 0 7.332-3.282 7.332-7.332 0-4.049-3.282-7.332-7.332-7.332s-7.332 3.283-7.332 7.332c0 4.05 3.283 7.332 7.332 7.332z"/></g></svg>
      </div>
      
    </div>
  
        <nav>
            {% include "home/nav.html" %}
        </nav>
        
        <div class="slides">
          <div class="slide" id="1">
            {% include 'home/home_child.html' %}
          </div>
          <div class="slide" id="2">
            {% include 'home/about_itea.html' %}
          </div>
          <div class="slide" id="3">
            {% include 'home/about_us.html' %}
          </div>
          <div class="slide" id="4">
            {% include 'home/work.html' %}
          </div>
          <div class="slide" id="5">
            {% include 'home/dashboard.html' %}
          </div>
        </div>

        <div class="footer">
          {% include 'home/footer.html' %}
        </div>

    
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"><\/script>')</script>

    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    
    <script src="{% static 'js/datepicker.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">
    $(document).ready(function() {

        

        // navigation click actions 
        $('.scroll-link').on('click', function(event){
            event.preventDefault();
            var sectionID = $(this).attr("data-id");
            scrollToID('#' + sectionID, 750);
        });
        // scroll to top action
        $('.scroll-top').on('click', function(event) {
            event.preventDefault();
            $('html, body').animate({scrollTop:0}, 'slow');         
        });
        // mobile nav toggle
        $('#nav-toggle').on('click', function (event) {
            event.preventDefault();
            $('#main-nav').toggleClass("open");
        });
    });
    // scroll function
    function scrollToID(id, speed){
        var offSet = 0;
        var targetOffset = $(id).offset().top - offSet;
        var mainNav = $('#main-nav');
        $('html,body').animate({scrollTop:targetOffset}, speed);
        if (mainNav.hasClass("open")) {
            mainNav.css("height", "1px").removeClass("in").addClass("collapse");
            mainNav.removeClass("open");
        }
    }
    if (typeof console === "undefined") {
        console = {
            log: function() { }
        };
    }
    </script>
</body>
</html>

templates/home/home_child.html
{% load static %}
<div class="content first-content">
  <div class="container-fluid">
      <div class="col-md-3">
          <div class="author-image"><img src="{% static 'img/author_image.png' %}" alt=""></div>
      </div>
      <div class="col-md-9">
          <h2>FINANCIAL MANAGEMENT SOFTWARE FOR ITEA</h2>
          <p><em>This is mainly a demo financial management software for ITEA.</em></p>
          <div class="fb-btn"><a href="https://www.facebook.com/shafik.te/" target="_blank">My FB Account</a></div>
          {% if user.is_authenticated %}
          <div class="fb-btn"><a href="{% url 'notice:notice-board' %}" target="_blank">Go Dashboard</a></div>
          {% endif %}
      </div>
  </div>
</div>

templates/home/nav.html
{% load static%}
  <div class="logo">
     <img src="{% static 'img/logo.png'%}" alt="">
  </div>
  <div class="mini-logo">
      <img src="{% static 'img/mini_logo.png' %}" alt="">
  </div>
  <ul>
    <li><a href="#1"><i class="fa fa-home"></i> <em>Home</em></a></li>
    <li><a href="#2"><i class="fa fa-user"></i> <em>About ITEA</em></a></li>
    <li><a href="#3"><i class="fa fa-group"></i> <em>About Us</em></a></li>
    <li><a href="#4"><i class="fa fa-image"></i> <em>Work</em></a></li>
    <li><a href="#5"><i class="fa fa-arrow-right"></i> <em>Enter</em></a></li>
  </ul>

templates/home/work.html
{% load static %}

<div class="content fourth-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 col-sm-6">
                <div class="item">
                    <div class="thumb">
                        <a href="{% static 'img/first_big_item.jpg' %}" data-lightbox="image-1"><div class="hover-effect">
                            <div class="hover-content">
                                <h2>Number One</h2>
                                <p>Quisque sit amet lacus in diam pretium faucibus. Cras vel justo lorem.</p>
                            </div>
                        </div></a>
                        <div class="image">
                            <img src="{% static 'img/first_item.jpg' %}">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="item">
                    <div class="thumb">
                        <a href="{% static 'img/second_big_item.jpg' %}" data-lightbox="image-1"><div class="hover-effect">
                            <div class="hover-content">
                                <h2>Number Two</h2>
                                <p>Donec eget dictum tellus. Curabitur a interdum diam. Nulla vestibulum porttitor porta.</p>
                            </div>
                        </div></a>
                        <div class="image">
                            <img src="{% static 'img/second_item.jpg' %}">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="item">
                    <div class="thumb">
                        <a href="{% static 'img/third_big_item.jpg' %}" data-lightbox="image-1"><div class="hover-effect">
                            <div class="hover-content">
                                <h2>Number Three</h2>
                                <p>Cras varius dolor et augue fringilla, eu commodo sapien iaculis.</p>
                            </div>
                        </div></a>
                        <div class="image">
                            <img src="{% static 'img/third_item.jpg' %}">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="item">
                    <div class="thumb">
                        <a href="{% static 'img/fourth_big_item.jpg' %}" data-lightbox="image-1"><div class="hover-effect">
                            <div class="hover-content">
                                <h2>Number Four</h2>
                                <p>Vestibulum augue ex, finibus sit amet nisi id, maximus ultrices ipsum.</p>
                            </div>
                        </div></a>
                        <div class="image">
                            <img src="{% static 'img/fourth_item.jpg' %}">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="item">
                    <div class="thumb">
                        <a href="{% static 'img/fifth_big_item.jpg' %}" data-lightbox="image-1"><div class="hover-effect">
                            <div class="hover-content">
                                <h2>Fifth Item</h2>
                                <p>Donec commodo, ex nec rutrum venenatis, nisi nisl malesuada magna.</p>
                            </div>
                        </div></a>
                        <div class="image">
                            <img src="{% static 'img/fifth_item.jpg' %}">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="item">
                    <div class="thumb">
                        <a href="{% static 'img/sixth_big_item.jpg' %}" data-lightbox="image-1"><div class="hover-effect">
                            <div class="hover-content">
                                <h2>Sixth Item</h2>
                                <p>Maecenas dapibus neque sed nisl consectetur, id semper nisi egestas.</p>
                            </div>
                        </div></a>
                        <div class="image">
                            <img src="{% static 'img/sixth_item.jpg' %}">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="item">
                    <div class="thumb">
                        <a href="{% static 'img/seventh_big_item.jpg' %}" data-lightbox="image-1"><div class="hover-effect">
                            <div class="hover-content">
                                <h2>Number Seven</h2>
                                <p>Etiam aliquet, est id varius fringilla, eros libero pellentesque lectus.</p>
                            </div>
                        </div></a>
                        <div class="image">
                            <img src="{% static 'img/seventh_item.jpg' %}">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="item">
                    <div class="thumb">
                        <a href="{% static 'img/eight_big_item.jpg' %}" data-lightbox="image-1"><div class="hover-effect">
                            <div class="hover-content">
                                <h2>Number Eight</h2>
                                <p>Vestibulum augue ex, finibus sit amet nisi id, maximus ultrices ipsum.</p>
                            </div>
                        </div></a>
                        <div class="image">
                            <img src="{% static 'img/eight_item.jpg' %}">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="item">
                    <div class="thumb">
                        <a href="{% static 'img/ninth_big_item.jpg' %}" data-lightbox="image-1"><div class="hover-effect">
                            <div class="hover-content">
                                <h2>Number Nine</h2>
                                <p>Orci varius natoque penatibus et magnis dis parturient montes.</p>
                            </div>
                        </div></a>
                        <div class="image">
                            <img src="{% static 'img/ninth_item.jpg' %}">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="item">
                    <div class="thumb">
                        <a href="{% static 'img/fifth_big_item.jpg' %}" data-lightbox="image-1"><div class="hover-effect">
                            <div class="hover-content">
                                <h2>Number Ten</h2>
                                <p>Vestibulum augue ex, finibus sit amet nisi id, maximus ultrices ipsum.</p>
                            </div>
                        </div></a>
                        <div class="image">
                            <img src="{% static 'img/fifth_item.jpg' %}">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="item">
                    <div class="thumb">
                        <a href="{% static 'img/first_big_item.jpg' %}" data-lightbox="image-1"><div class="hover-effect">
                            <div class="hover-content">
                                <h2>Eleventh Item</h2>
                                <p>Cras varius dolor et augue fringilla, eu commodo sapien iaculis.</p>
                            </div>
                        </div></a>
                        <div class="image">
                            <img src="{% static 'img/first_item.jpg' %}">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="item">
                    <div class="thumb">
                        <a href="{% static 'img/second_big_item.jpg' %}" data-lightbox="image-1"><div class="hover-effect">
                            <div class="hover-content">
                                <h2>Twelvth Item</h2>
                                <p>Etiam tincidunt magna ex, sit amet lobortis felis bibendum id.</p>
                            </div>
                        </div></a>
                        <div class="image">
                            <img src="{% static 'img/second_item.jpg' %}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>