balance/urls.py
from django.urls import path
from django.views.generic import TemplateView

from balance.views.transaction import TransactionListView, TransactionCreate, TransactionDetailView, \
    TransactionUpdateView, TransactionDeleteView, TransactionQuery, DueMonthQuery, MyDueMonths, DownloadCSV
from balance.views.exp_transaction import ExpTransactionListView, ExpTransactionCreate, ExpTransactionDetailView, \
    ExpTransactionUpdateView, ExpTransactionDeleteView, ExpTransactionQuery
from balance.views.incm_transaction import IncmTransactionListView, IncmTransactionCreate, IncmTransactionDetailView, \
    IncmTransactionUpdateView, IncmTransactionDeleteView, IncmTransactionQuery
from balance.views.org_views import OrganizationalView

app_name = "balance"

urlpatterns = [
    path('dashboard/', TemplateView.as_view(template_name="balance/balance_dashboard.html"), name='balance-dashboard'),
    path('transaction/list/', TransactionListView.as_view(), name='transaction-list'),
    path('transaction/create/', TransactionCreate.as_view(), name='transaction-create'),
    path('transaction/<int:pk>/', TransactionDetailView.as_view(), name='transaction-details'),
    path('transaction/<int:pk>/update/', TransactionUpdateView.as_view(), name='transaction-edit'),
    path('transaction/<int:pk>/delete/', TransactionDeleteView.as_view(), name='transaction-delete'),
    path('transaction/query/', TransactionQuery.as_view(), name='transaction-query'),
    path('transaction/query-due/', DueMonthQuery.as_view(), name='transaction-query-due'),
    path('transaction/my-due/', MyDueMonths.as_view(), name='transaction-my-due'),
    path('transaction/download/', DownloadCSV.as_view(), name='transaction-download'),
]
EXPENSE_URL = [
    path('exp-transaction/list/', ExpTransactionListView.as_view(), name='exp-transaction-list'),
    path('exp-transaction/create/', ExpTransactionCreate.as_view(), name='exp-transaction-create'),
    path('exp-transaction/<int:pk>/', ExpTransactionDetailView.as_view(), name='exp-transaction-details'),
    path('exp-transaction/<int:pk>/update/', ExpTransactionUpdateView.as_view(), name='exp-transaction-edit'),
    path('exp-transaction/<int:pk>/delete/', ExpTransactionDeleteView.as_view(), name='exp-transaction-delete'),
    path('exp-transaction/query/', ExpTransactionQuery.as_view(), name='exp-transaction-query'),
]

INCOME_URL = [
    path('incm-transaction/list/', IncmTransactionListView.as_view(), name='incm-transaction-list'),
    path('incm-transaction/create/', IncmTransactionCreate.as_view(), name='incm-transaction-create'),
    path('incm-transaction/<int:pk>/', IncmTransactionDetailView.as_view(), name='incm-transaction-details'),
    path('incm-transaction/<int:pk>/update/', IncmTransactionUpdateView.as_view(), name='incm-transaction-edit'),
    path('incm-transaction/<int:pk>/delete/', IncmTransactionDeleteView.as_view(), name='incm-transaction-delete'),
    path('incm-transaction/query/', IncmTransactionQuery.as_view(), name='incm-transaction-query'),
]
OTHERS_URL = [
    path('organization/', OrganizationalView.as_view(), name='organization'),
]

urlpatterns += EXPENSE_URL + INCOME_URL + OTHERS_URL

itea/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name="home/home.html"), name='home'),
    path('members/', include('members.urls', namespace='members')),
    path('balance/', include('balance.urls', namespace='balance')),
    path('notice/', include('notice.urls', namespace='notice')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from members.views import SignUp, UserListView, UserDetailView, UserBasicUpdateView, UserProfileUpdateView, \
    ActivateMemberRequest

app_name = "member"

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('list/', UserListView.as_view(), name='member-list'),
    path('details/<int:pk>/', UserDetailView.as_view(), name='member-details'),
    path('basic/<int:pk>/update', UserBasicUpdateView.as_view(), name='basic-update'),
    path('profile/<int:pk>/update', UserProfileUpdateView.as_view(), name='profile-update'),
    path('activate/', ActivateMemberRequest.as_view(), name='activate'),
]

notice/urls.py
from django.urls import path

from notice.views import NoticeCreate, NoticeListView, NoticeDetailView, \
    NoticeUpdateView, NoticeDeleteView, NoticeBoard

app_name = "notice"

urlpatterns = [
    path('list/', NoticeListView.as_view(), name='notice-list'),
    path('create/', NoticeCreate.as_view(), name='notice-create'),
    path('<int:pk>/', NoticeDetailView.as_view(), name='notice-details'),
    path('<int:pk>/update/', NoticeUpdateView.as_view(), name='notice-edit'),
    path('<int:pk>/delete/', NoticeDeleteView.as_view(), name='notice-delete'),
    path('board/', NoticeBoard.as_view(), name='notice-board'),
]

balance/views/exp_transaction.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
# specific to this view
from django.utils import timezone
from django.views import View
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from balance.forms import DateForm
from balance.models.expense_transaction import ExpenseTransaction
from applibs.permission import FinancePermissionMixin
from members.models import User


class ExpTransactionListView(LoginRequiredMixin, ListView):
    """
    Show all Expense Transaction list
    """
    model = ExpenseTransaction
    template_name = 'balance/list_exp_transaction.html'
    context_object_name = 'transactions'

    def get_queryset(self, *args, **kwargs):
        query_dict = {
            "current": ExpenseTransaction.objects.get_current_month_exp_transaction(),
        }
        object_list = ExpenseTransaction.objects.filter(status=True)

        if self.request.GET.get('p'):
            object_list = query_dict.get(self.request.GET.get('p'))

        paginator = Paginator(object_list, 50)  # maping total object with this paginator
        page = self.request.GET.get('page')  # getting current page number
        try:
            transactions = paginator.page(page)
        except PageNotAnInteger:
            # if page is not an interger deliver first page
            transactions = paginator.page(1)
        except EmptyPage:
            # if page is out of range deliver last page
            transactions = paginator.page(paginator.num_pages)
        return transactions


class ExpTransactionCreate(FinancePermissionMixin, CreateView):
    """
        Create Transaction
    """
    template_name = 'balance/create_exp_transaction.html'
    model = ExpenseTransaction
    fields = ("expense_by", "amount", "expense_date", "expense_type", "expense_details")

    def get_success_url(self):
        return reverse_lazy('balance:exp-transaction-details', kwargs={'pk': self.object.id})


class ExpTransactionUpdateView(FinancePermissionMixin, UpdateView):
    """
    Update Transaction
    """
    model = ExpenseTransaction
    template_name = 'balance/update.html'
    context_object_name = 'transaction'
    fields = ("expense_by", "amount", "expense_date", "expense_type", "expense_details")

    def get_success_url(self):
        return reverse_lazy('balance:exp-transaction-details', kwargs={'pk': self.object.id})


class ExpTransactionDetailView(LoginRequiredMixin, DetailView):
    """
    Transaction Details
    """
    model = ExpenseTransaction
    template_name = 'balance/details_exp_transaction.html'
    context_object_name = 'transaction'


class ExpTransactionDeleteView(FinancePermissionMixin, DeleteView):
    """
    Delete transaction
    """
    model = ExpenseTransaction
    template_name = 'balance/delete_exp_transaction.html'
    context_object_name = 'transaction'
    success_url = reverse_lazy('balance:exp-transaction-list')

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.status = False
        self.object.save()
        return HttpResponseRedirect(success_url)


class ExpTransactionQuery(LoginRequiredMixin, View):
    """
        Query expense transaction by datepicker
    """

    def get(self, request, *args, **kwargs):
        return render(request, 'datepicker/datepicker.html', {"form": DateForm(), "name": "Expense"})

    def post(self, request, *args, **kwargs):
        data = self.request.POST.dict()
        start_date = timezone.datetime.strptime(data.get("start_date"), "%m/%d/%Y %H:%M %p").date()
        end_date = timezone.datetime.strptime(data.get("end_date"), "%m/%d/%Y %H:%M %p").date()
        user_id = data.get('user')
        user = None
        if user_id:
            user = get_object_or_404(User, id=int(user_id))
        queryset = ExpenseTransaction.objects.get_date_query_exp_transaction(start_date=start_date, end_date=end_date,
                                                                             user=user)
        total = queryset.aggregate(Sum('amount')).get('amount__sum')

        return render(request, 'balance/list_exp_transaction.html', {"transactions": queryset, "total": total})

balance/views/incm_transaction.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
# specific to this view
from django.utils import timezone
from django.views import View
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from applibs.permission import FinancePermissionMixin
from balance.forms import DateForm
from balance.models.income_transaction import IncomeTransaction
from members.models import User


class IncmTransactionListView(LoginRequiredMixin, ListView):
    """
    Show all income Transaction list
    """
    model = IncomeTransaction
    template_name = 'balance/list_incm_transaction.html'
    context_object_name = 'transactions'

    def get_queryset(self, *args, **kwargs):
        query_dict = {
            "current": IncomeTransaction.objects.get_current_month_incm_transaction(),
        }
        object_list = IncomeTransaction.objects.filter(status=True)
        if self.request.GET.get('p'):
            object_list = query_dict.get(self.request.GET.get('p'))

        paginator = Paginator(object_list, 20)  # maping total object with this paginator
        page = self.request.GET.get('page')  # getting current page number
        try:
            transactions = paginator.page(page)
        except PageNotAnInteger:
            # if page is not an interger deliver first page
            transactions = paginator.page(1)
        except EmptyPage:
            # if page is out of range deliver last page
            transactions = paginator.page(paginator.num_pages)
        return transactions


class IncmTransactionCreate(FinancePermissionMixin, CreateView):
    """
        Create Income Transaction
    """
    template_name = 'balance/create_incm_transaction.html'
    model = IncomeTransaction
    fields = ("received_by", "amount", "received_date", "received_details")

    def get_success_url(self):
        return reverse_lazy('balance:incm-transaction-details', kwargs={'pk': self.object.id})


class IncmTransactionUpdateView(FinancePermissionMixin, UpdateView):
    """
    Update Income Transaction
    """
    model = IncomeTransaction
    template_name = 'balance/update.html'
    context_object_name = 'transaction'
    fields = ("received_by", "amount", "received_date", "received_details")

    def get_success_url(self):
        return reverse_lazy('balance:incm-transaction-details', kwargs={'pk': self.object.id})


class IncmTransactionDetailView(LoginRequiredMixin, DetailView):
    """
    Transaction Details
    """
    model = IncomeTransaction
    template_name = 'balance/details_incm_transaction.html'
    context_object_name = 'transaction'


class IncmTransactionDeleteView(FinancePermissionMixin, DeleteView):
    """
    Delete transaction
    """
    model = IncomeTransaction
    template_name = 'balance/delete_incm_transaction.html'
    context_object_name = 'transaction'
    success_url = reverse_lazy('balance:incm-transaction-list')

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.status = False
        self.object.save()
        return HttpResponseRedirect(success_url)


class IncmTransactionQuery(LoginRequiredMixin, View):
    """
        Query income transaction by datepicker
    """

    def get(self, request, *args, **kwargs):
        return render(request, 'datepicker/datepicker.html', {"form": DateForm(), "name": "Income"})

    def post(self, request, *args, **kwargs):
        data = self.request.POST.dict()
        start_date = timezone.datetime.strptime(data.get("start_date"), "%m/%d/%Y %H:%M %p").date()
        end_date = timezone.datetime.strptime(data.get("end_date"), "%m/%d/%Y %H:%M %p").date()
        user_id = data.get('user')
        user = None
        if user_id:
            user = get_object_or_404(User, id=int(user_id))
        queryset = IncomeTransaction.objects.get_date_query_incm_transaction(start_date=start_date, end_date=end_date,
                                                                             user=user)
        total = queryset.aggregate(Sum('amount')).get('amount__sum')

        return render(request, 'balance/list_incm_transaction.html', {"transactions": queryset, "total": total})

balance/views/org_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.shortcuts import render
from django.views import View

from balance.models.transaction import Transaction
from balance.models.expense_transaction import ExpenseTransaction
from balance.models.income_transaction import IncomeTransaction


class OrganizationalView(LoginRequiredMixin, View):
    """
        For individual due months query
    """

    def get(self, request):
        monthly_amount_by_members = Transaction.objects.filter(status=True,
                                                               transaction_type='monthly'
                                                               ).aggregate(Sum('amount')
                                                                           ).get('amount__sum')
        additional_amount_by_members = Transaction.objects.filter(status=True,
                                                                  transaction_type='additional'
                                                                  ).aggregate(Sum('amount')
                                                                              ).get('amount__sum')
        others_amount_by_members = Transaction.objects.filter(status=True,
                                                              transaction_type='others'
                                                              ).aggregate(Sum('amount')
                                                                          ).get('amount__sum')
        total_expense = ExpenseTransaction.objects.filter(status=True
                                                          ).aggregate(Sum('amount')
                                                                      ).get('amount__sum')
        total_income = IncomeTransaction.objects.filter(status=True
                                                        ).aggregate(Sum('amount')
                                                                    ).get('amount__sum')

        context = {
            "monthy": monthly_amount_by_members,
            "additional": additional_amount_by_members,
            "others": others_amount_by_members,
            "total_expense": total_expense,
            "total_income": total_income
        }
        return render(request, 'balance/organization.html', context)

templates/balance/balance_dashboard.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load grouptags %}

{% block title %}Balance Dashboard{% endblock %}

{% block content %}
<div class="content fifth-content">
    <div class="container-fluid">
        <div class="col-md-12 bottom">
            <div class="row top-margin">
                <div class="col-md-4">
                  <fieldset>
                      <h2 id="head-text">Current Month Transaction</h2>
                      <a href="{% url 'balance:transaction-list'%}?p=me_current">
                          <button type="link" id="form-submit " class="btn top-spacing ">My Transaction</button>
                      </a>
                      <a href="{% url 'balance:transaction-list'%}?p=all_current">
                          <button type="link" id="form-submit" class="btn top-spacing">All Members' </button>
                      </a>
                      <a href="{% url 'balance:exp-transaction-list'%}?p=current">
                          <button type="link" id="form-submit" class="btn top-spacing">Expense</button>
                      </a>
                      <a href="{% url 'balance:incm-transaction-list'%}?p=current">
                          <button type="link" id="form-submit" class="btn top-spacing">Income</button>
                      </a>
                  </fieldset>
                </div>
                <div class="col-md-4">
                  <fieldset>
                      <h2 id="head-text">All Transaction</h2>
                      <a href="{% url 'balance:transaction-list'%}?p=me_all">
                          <button type="link" id="form-submit" class="btn top-spacing">My Transactions</button>
                      </a>
                      <a href="{% url 'balance:transaction-my-due'%}?p=me_all">
                          <button type="link" id="form-submit" class="btn top-spacing">My Due Months</button>
                      </a>

                      <a href="{% url 'balance:transaction-list' %}">
                          <button type="link" id="form-submit" class="btn top-spacing">All Members'</button>
                      </a>
                      <a href="{% url 'balance:exp-transaction-list'%}">
                          <button type="link" id="form-submit" class="btn top-spacing">Expense</button>
                      </a>
                      <a href="{% url 'balance:incm-transaction-list' %}">
                          <button type="link" id="form-submit" class="btn top-spacing">Income</button>
                      </a>
                  </fieldset>
                </div>
                <div class="col-md-4">
                  <fieldset>
                      <h2 id="head-text">Query By Date</h2>
                      <a href="{% url 'balance:transaction-query' %}">
                          <button type="link" id="form-submit" class="btn top-spacing">Transaction</button>
                      </a>
                      <a href="{% url 'balance:exp-transaction-query' %}">
                          <button type="link" id="form-submit" class="btn top-spacing">Expense</button>
                      </a>
                      <a href="{% url 'balance:incm-transaction-query' %}">
                          <button type="link" id="form-submit" class="btn top-spacing">Income</button>
                      </a>
                  </fieldset>
                </div>
            </div>
        <!-- Only For Finance Executive-->
        {% if request.user|has_group:"Finance"%}
            <div class="row top-margin" id="bottom">
                <div class="col-md-4">
                  <fieldset>
                      <h2 id="head-text">Create Member's Transaction</h2>
                      <a href="{% url 'balance:transaction-create'%}">
                          <button type="link" id="form-submit " class="btn top-spacing ">Click Here</button>
                      </a>
                  </fieldset>
                </div>
                <div class="col-md-4">
                  <fieldset>
                      <h2 id="head-text">Create Expense Transaction</h2>
                      <a href="{% url 'balance:exp-transaction-create'%}?p=me_all">
                          <button type="link" id="form-submit" class="btn top-spacing">Click Here</button>
                      </a>
                  </fieldset>
                </div>
                <div class="col-md-4">
                  <fieldset>
                      <h2 id="head-text">Create Income Transaction</h2>
                      <a href="{% url 'balance:incm-transaction-create' %}">
                          <button type="link" id="form-submit" class="btn top-spacing">Click Here</button>
                      </a>
                  </fieldset>
                </div>
            </div>
            <div class="row top-margin" id="bottom">
                <div class="col-md-4">
                  <fieldset>
                      <h2 id="head-text">Get Member's Due Months</h2>
                      <a href="{% url 'balance:transaction-query-due' %}">
                          <button type="link" id="form-submit" class="btn top-spacing">Click Here</button>
                      </a>
                  </fieldset>
                </div>
                 <div class="col-md-4">
                  <fieldset>
                      <h2 id="head-text">Activate Membership Request</h2>
                      <a href="{% url 'member:activate' %}">
                          <button type="link" id="form-submit" class="btn top-spacing">Click Here</button>
                      </a>
                  </fieldset>
                </div>
            </div>
        {% endif %}
        <div class="row top-margin" id="bottom">
                <div class="col-md-4">
                  <fieldset>
                      <h2 id="head-text">Go to Notice Board</h2>
                      <a href="{% url 'notice:notice-board' %}">
                          <button type="link" id="form-submit" class="btn top-spacing">Click Here</button>
                      </a>
                  </fieldset>
                </div>
                <div class="col-md-4">
                      <fieldset>
                          <h2 id="head-text">Org. Overview</h2>
                          <a href="{% url 'balance:organization' %}">
                              <button type="link" id="form-submit" class="btn top-spacing">Click Here</button>
                          </a>
                      </fieldset>
                 </div>
            </div>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
{% endblock %}

templates/balance/create_exp_transaction.html
{% extends 'base/base_out.html' %}
{% load widget_tweaks %}

{% block title %}Expense Transaction Create{% endblock %}

{% block content %}
<div class="content first-content">
  <div class="container-fluid">
      <div class="col-md-9 bottom">
          <h2>Expense Transaction</h2>
          <form method="post">
            {% csrf_token %}
              {% for field in form %}
              <div class="form-group" >
                {{field.errors}}
                {{field.label_tag}}
                {% render_field field class="form-control" placeholder=field.help_text %}
              </div>
              {% endfor %}
              <button class="btn btn-primary" type="submit">Save</button>
          </form>

      </div>
  </div>
</div>

{% endblock %}

templates/balance/create_incm_transaction.html
{% extends 'base/base_out.html' %}
{% load widget_tweaks %}

{% block title %}Income Transaction Create{% endblock %}

{% block content %}
<div class="content first-content">
  <div class="container-fluid">
      <div class="col-md-9 bottom">
          <h2>Income Transaction</h2>
          <form method="post">
            {% csrf_token %}
              {% for field in form %}
              <div class="form-group" >
                {{field.errors}}
                {{field.label_tag}}
                {% render_field field class="form-control" placeholder=field.help_text %}
              </div>
              {% endfor %}
              <button class="btn btn-primary" type="submit">Save</button>
          </form>

      </div>
  </div>
</div>

{% endblock %}

templates/balance/details_incm_transaction.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% load grouptags %}

{% block title %}Income Transaction Details{% endblock %}

{% block content %}
<div class="content first-content">
  <div class="container-fluid">
      <div class="col-md-12 bottom">
          <h2>Income Transaction Details </h2>
          <p><em>Transaction ID: </em>{{ transaction.income_guid }}</p>
          <p><em>Received By: </em> {{ transaction.received_by}}</p>
          <p><em>Receive Amount: </em> {{ transaction.amount}}</p>
          <p><em>Receive Date: </em> {{ transaction.received_date}}</p>
          <p><em>Receive Details: </em> {{ transaction.received_details }}</p>
          <p><em>Income Created at: </em> {{ transaction.created_at}}</p>
          <p><em>Income Updated at: </em> {{ transaction.updated_at}}</p>
          {% if request.user|has_group:"Finance"%}
          <div class="fb-btn"><a href="{% url 'balance:incm-transaction-edit' transaction.id %}">Edit</a></div>
          <div class="fb-btn"><a href="{% url 'balance:incm-transaction-delete' transaction.id %}">Delete</a></div>
          <div class="fb-btn"><a href="{% url 'balance:incm-transaction-create' %}">Create Another</a></div>
          {% endif %}

      </div>
  </div>
</div>{% endblock %}

templates/balance/details_transaction.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% load grouptags %}

{% block title %}Transaction Details{% endblock %}

{% block content %}
<div class="content first-content">
  <div class="container-fluid">
      <div class="col-md-12 bottom">
          <h2>Transaction Details </h2>
          <p><em>Transaction To: </em>{{ transaction.user.name }}</p>
          <p><em>Transaction ID: </em> {{ transaction.transaction_guid}}</p>
          <p><em>Transaction Amount: </em> {{ transaction.amount}}</p>
          <p><em>Transaction Date: </em> {{ transaction.transaction_date}}</p>
          <p><em>Transaction Type: </em> {{ transaction.transaction_type}}</p>
          <p><em>Transaction Details: </em> {{ transaction.transaction_details }}</p>
          <p><em>Transaction Created at: </em> {{ transaction.created_at}}</p>
          <p><em>Transaction Updated at: </em> {{ transaction.updated_at}}</p>
          {% if request.user|has_group:"Finance"%}
          <div class="fb-btn"><a href="{% url 'balance:transaction-edit' transaction.id %}">Edit</a></div>
          <div class="fb-btn"><a href="{% url 'balance:transaction-delete' transaction.id %}">Delete</a></div>
          <div class="fb-btn"><a href="{% url 'balance:transaction-create'%}">Create Another</a></div>
          {% endif %}

      </div>
  </div>
</div>{% endblock %}

templates/balance/list_transaction.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load grouptags %}
{% load static %}


{% block title %}Transaction List{% endblock %}

{% block content %}
<div class="content fourth-content">
    <div class="container-fluid">
        <div class="col-md-12 bottom">
            <div class="left-content">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i> <h2 id="head-text">Transaction Lists:</h2>
                </div>
                <div class="card-block">
                    <table class="table table-bordered table-striped table-sm text-center">
                        <thead>
                        <tr>
                            <th> <h3 class="text-center" id="text"> Name</h3> </th>
                            <th> <h3 class="text-center" id="text"> Amount</h3> </th>
                            <th> <h3 class="text-center" id="text"> Transaction Date</h3> </th>
                            <th> <h3 class="text-center" id="text"> Transaction type</h3> </th>
                            {% if request.user|has_group:"Finance" %}
                            <th> <h3 class="text-center" id="text"> Edit</h3> </th>
                            <th> <h3 class="text-center" id="text"> Delete</h3> </th>
                            {% endif %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for transaction in transactions %}
                        <tr>
                            <td><a href="#" class="test-success"><span class="btn text-dark" id="table-text">{{ transaction.user.name }}</span></a></td>
                            <td><a href="#" class="test-success"><span class="btn text-dark" id="table-text">{{ transaction.amount }}</span></a></td>
                            <td><a href="#" class="test-success"><span class="btn text-dark" id="table-text">{{ transaction.transaction_date }}</span></a></td>
                            <td><a href="#" class="test-success"><span class="btn text-dark" id="table-text">{{ transaction.transaction_type }}</span></a></td>
                            {% if request.user|has_group:"Finance" %}
                            <td><a href="{% url 'balance:transaction-edit' transaction.id %}" class="test-success"><span class="btn text-dark" id="table-text">Click Edit</span></a></td>
                            <td><a href="{% url 'balance:transaction-delete' transaction.id %}" class="test-success"><span class="btn text-dark" id="table-text">Click Delete</span></a></td>
                            {% endif %}

                        </tr>
                        {% endfor %}
                        {% if total %}
                        <tr>
                            <td><a href="#" class="test-success"><span class="btn text-dark" id="table-text">Total =</span></a></td>
                            <td><a href="#" class="test-success"><span class="btn text-dark" id="table-text">{{ total }}</span></a></td>
                        </tr>
                        {% endif %}
                        </tbody>

                    </table>
                    {% if request.user|has_group:"Finance" and download %}
                        <a href="{% url 'balance:transaction-download' %}" id="head-text">Download Query File</a>
                    {% endif %}
                    {% include "pagination/pagination.html" with page=transactions %}
                </div>
          </div>
        </div>
    </div>
</div>
{% endblock %}