balance/urls.py
from django.urls import path
from django.views.generic import TemplateView

from balance.views.transaction import TransactionListView, TransactionCreate, TransactionDetailView, \
    TransactionUpdateView, TransactionDeleteView, TransactionQuery, DueMonthQuery, MyDueMonths, DownloadCSV
from balance.views.exp_transaction import ExpTransactionListView, ExpTransactionCreate, ExpTransactionDetailView, \
    ExpTransactionUpdateView, ExpTransactionDeleteView, ExpTransactionQuery
from balance.views.incm_transaction import IncmTransactionListView, IncmTransactionCreate, IncmTransactionDetailView, \
    IncmTransactionUpdateView, IncmTransactionDeleteView, IncmTransactionQuery
from balance.views.org_views import OrganizationalView

app_name = "balance"

urlpatterns = [
    path('dashboard/', TemplateView.as_view(template_name="balance/balance_dashboard.html"), name='balance-dashboard'),
    path('transaction/list/', TransactionListView.as_view(), name='transaction-list'),
    path('transaction/create/', TransactionCreate.as_view(), name='transaction-create'),
    path('transaction/<int:pk>/', TransactionDetailView.as_view(), name='transaction-details'),
    path('transaction/<int:pk>/update/', TransactionUpdateView.as_view(), name='transaction-edit'),
    path('transaction/<int:pk>/delete/', TransactionDeleteView.as_view(), name='transaction-delete'),
    path('transaction/query/', TransactionQuery.as_view(), name='transaction-query'),
    path('transaction/query-due/', DueMonthQuery.as_view(), name='transaction-query-due'),
    path('transaction/my-due/', MyDueMonths.as_view(), name='transaction-my-due'),
    path('transaction/download/', DownloadCSV.as_view(), name='transaction-download'),
]
EXPENSE_URL = [
    path('exp-transaction/list/', ExpTransactionListView.as_view(), name='exp-transaction-list'),
    path('exp-transaction/create/', ExpTransactionCreate.as_view(), name='exp-transaction-create'),
    path('exp-transaction/<int:pk>/', ExpTransactionDetailView.as_view(), name='exp-transaction-details'),
    path('exp-transaction/<int:pk>/update/', ExpTransactionUpdateView.as_view(), name='exp-transaction-edit'),
    path('exp-transaction/<int:pk>/delete/', ExpTransactionDeleteView.as_view(), name='exp-transaction-delete'),
    path('exp-transaction/query/', ExpTransactionQuery.as_view(), name='exp-transaction-query'),
]

INCOME_URL = [
    path('incm-transaction/list/', IncmTransactionListView.as_view(), name='incm-transaction-list'),
    path('incm-transaction/create/', IncmTransactionCreate.as_view(), name='incm-transaction-create'),
    path('incm-transaction/<int:pk>/', IncmTransactionDetailView.as_view(), name='incm-transaction-details'),
    path('incm-transaction/<int:pk>/update/', IncmTransactionUpdateView.as_view(), name='incm-transaction-edit'),
    path('incm-transaction/<int:pk>/delete/', IncmTransactionDeleteView.as_view(), name='incm-transaction-delete'),
    path('incm-transaction/query/', IncmTransactionQuery.as_view(), name='incm-transaction-query'),
]
OTHERS_URL = [
    path('organization/', OrganizationalView.as_view(), name='organization'),
]

urlpatterns += EXPENSE_URL + INCOME_URL + OTHERS_URL

itea/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name="home/home.html"), name='home'),
    path('members/', include('members.urls', namespace='members')),
    path('balance/', include('balance.urls', namespace='balance')),
    path('notice/', include('notice.urls', namespace='notice')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from members.views import SignUp, UserListView, UserDetailView, UserBasicUpdateView, UserProfileUpdateView, \
    ActivateMemberRequest

app_name = "member"

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('list/', UserListView.as_view(), name='member-list'),
    path('details/<int:pk>/', UserDetailView.as_view(), name='member-details'),
    path('basic/<int:pk>/update', UserBasicUpdateView.as_view(), name='basic-update'),
    path('profile/<int:pk>/update', UserProfileUpdateView.as_view(), name='profile-update'),
    path('activate/', ActivateMemberRequest.as_view(), name='activate'),
]

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
          <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/fontAwesome.css' %}">
        <link rel="stylesheet" href="{% static 'css/light-box.css' %}">
        <link rel="stylesheet" href="{% static 'css/templatemo-main.css' %}">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">

        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    </head>

<body>

    <div class="sequence">

      <div class="seq-preloader">
        <svg width="39" height="16" viewBox="0 0 39 16" xmlns="http://www.w3.org/2000/svg" class="seq-preload-indicator"><g fill="#F96D38"><path class="seq-preload-circle seq-preload-circle-1" d="M3.999 12.012c2.209 0 3.999-1.791 3.999-3.999s-1.79-3.999-3.999-3.999-3.999 1.791-3.999 3.999 1.79 3.999 3.999 3.999z"/><path class="seq-preload-circle seq-preload-circle-2" d="M15.996 13.468c3.018 0 5.465-2.447 5.465-5.466 0-3.018-2.447-5.465-5.465-5.465-3.019 0-5.466 2.447-5.466 5.465 0 3.019 2.447 5.466 5.466 5.466z"/><path class="seq-preload-circle seq-preload-circle-3" d="M31.322 15.334c4.049 0 7.332-3.282 7.332-7.332 0-4.049-3.282-7.332-7.332-7.332s-7.332 3.283-7.332 7.332c0 4.05 3.283 7.332 7.332 7.332z"/></g></svg>
      </div>

    </div>


        <nav>
          <div class="logo">
            <img src="{% static 'img/logo.png'%}" alt="">
          </div>
          <div class="mini-logo">
              <img src="{% static 'img/mini_logo.png' %}" alt="">
          </div>
          <ul>
            <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> <em>Home</em></a></li>
            <li><a href="{% url 'member:member-details' request.user.id %}"><i class="fa fa-user"></i> <em>Profile</em></a></li>
            <li><a href="{% url 'balance:balance-dashboard' %}"><i class="fa fa-dashboard"></i> <em>My Dashboard</em></a></li>
            <li><a href="{% url 'member:member-list' %}"><i class="fa fa-image"></i> <em>Members</em></a></li>
            <li><a href="{% url 'member:logout' %}"><i class="fa fa-user"></i> <em>Logout</em></a></li>
          </ul>
        </nav>

        <div class="slides">
          <div class="slide">
            {% block content %}
            {% endblock %}
          </div>
        </div>

        <div class="footer">
            {% include 'base/footer.html' %}
        </div>


   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
</body>
</html>

templates/base/base_date.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
          <title>{% block title %}{% endblock %}</title>
<!--
Moonlight Template
http://www.templatemo.com/tm-512-moonlight
-->
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
{#        <link rel="apple-touch-icon" href="apple-touch-icon.png">#}
{#        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">#}
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/fontAwesome.css' %}">
        <link rel="stylesheet" href="{% static 'css/light-box.css' %}">
        <link rel="stylesheet" href="{% static 'css/templatemo-main.css' %}">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">

        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>

        <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

    </head>

<body>

    <div class="sequence">

      <div class="seq-preloader">
        <svg width="39" height="16" viewBox="0 0 39 16" xmlns="http://www.w3.org/2000/svg" class="seq-preload-indicator"><g fill="#F96D38"><path class="seq-preload-circle seq-preload-circle-1" d="M3.999 12.012c2.209 0 3.999-1.791 3.999-3.999s-1.79-3.999-3.999-3.999-3.999 1.791-3.999 3.999 1.79 3.999 3.999 3.999z"/><path class="seq-preload-circle seq-preload-circle-2" d="M15.996 13.468c3.018 0 5.465-2.447 5.465-5.466 0-3.018-2.447-5.465-5.465-5.465-3.019 0-5.466 2.447-5.466 5.465 0 3.019 2.447 5.466 5.466 5.466z"/><path class="seq-preload-circle seq-preload-circle-3" d="M31.322 15.334c4.049 0 7.332-3.282 7.332-7.332 0-4.049-3.282-7.332-7.332-7.332s-7.332 3.283-7.332 7.332c0 4.05 3.283 7.332 7.332 7.332z"/></g></svg>
      </div>

    </div>


        <nav>
          <div class="logo">
            <img src="{% static 'img/logo.png'%}" alt="">
          </div>
          <div class="mini-logo">
              <img src="{% static 'img/mini_logo.png' %}" alt="">
          </div>
          <ul>
            <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> <em>Home</em></a></li>
            <li><a href="{% url 'member:member-details' request.user.id %}"><i class="fa fa-user"></i> <em>Profile</em></a></li>
            <li><a href="{% url 'balance:balance-dashboard' %}"><i class="fa fa-money"></i> <em>Balance History</em></a></li>
            <li><a href="{% url 'member:member-list' %}"><i class="fa fa-image"></i> <em>Members</em></a></li>
            <li><a href="{% url 'member:logout' %}"><i class="fa fa-user"></i> <em>Logout</em></a></li>
          </ul>
        </nav>

        <div class="slides">
          <div class="slide">
            {% block content %}
            {% endblock %}
          </div>
{#          <div class="slide" id="2">#}
{#            {% include "test/about_itea.html" %}#}
{#          </div>#}
{#          <div class="slide" id="3">#}
{#            {% include 'test/about_us.html' %}#}
{#          </div>#}
{#          <div class="slide" id="4">#}
{#            {% include 'test/work.html' %}#}
{#          </div>#}
{#          <div class="slide" id="5">#}
{#            {% include "test/dashboard.html" %}#}
{#          </div>#}
        </div>

        <div class="footer">
            {% include 'base/footer.html' %}
        </div>


    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
{#    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>#}
{#    <script type="text/javascript">#}
{#    $(document).ready(function() {#}
{##}
{##}
{##}
{#        // navigation click actions#}
{#        $('.scroll-link').on('click', function(event){#}
{#            event.preventDefault();#}
{#            var sectionID = $(this).attr("data-id");#}
{#            scrollToID('#' + sectionID, 750);#}
{#        });#}
{#        // scroll to top action#}
{#        $('.scroll-top').on('click', function(event) {#}
{#            event.preventDefault();#}
{#            $('html, body').animate({scrollTop:0}, 'slow');#}
{#        });#}
{#        // mobile nav toggle#}
{#        $('#nav-toggle').on('click', function (event) {#}
{#            event.preventDefault();#}
{#            $('#main-nav').toggleClass("open");#}
{#        });#}
{#    });#}
{#    // scroll function#}
{#    function scrollToID(id, speed){#}
{#        var offSet = 0;#}
{#        var targetOffset = $(id).offset().top - offSet;#}
{#        var mainNav = $('#main-nav');#}
{#        $('html,body').animate({scrollTop:targetOffset}, speed);#}
{#        if (mainNav.hasClass("open")) {#}
{#            mainNav.css("height", "1px").removeClass("in").addClass("collapse");#}
{#            mainNav.removeClass("open");#}
{#        }#}
{#    }#}
{#    if (typeof console === "undefined") {#}
{#        console = {#}
{#            log: function() { }#}
{#        };#}
{#    }#}
{#    </script>#}
</body>
</html>

templates/base/base_out.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
          <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/fontAwesome.css' %}">
        <link rel="stylesheet" href="{% static 'css/light-box.css' %}">
        <link rel="stylesheet" href="{% static 'css/templatemo-main.css' %}">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">

        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    </head>

<body>

    <div class="sequence">

      <div class="seq-preloader">
        <svg width="39" height="16" viewBox="0 0 39 16" xmlns="http://www.w3.org/2000/svg" class="seq-preload-indicator"><g fill="#F96D38"><path class="seq-preload-circle seq-preload-circle-1" d="M3.999 12.012c2.209 0 3.999-1.791 3.999-3.999s-1.79-3.999-3.999-3.999-3.999 1.791-3.999 3.999 1.79 3.999 3.999 3.999z"/><path class="seq-preload-circle seq-preload-circle-2" d="M15.996 13.468c3.018 0 5.465-2.447 5.465-5.466 0-3.018-2.447-5.465-5.465-5.465-3.019 0-5.466 2.447-5.466 5.465 0 3.019 2.447 5.466 5.466 5.466z"/><path class="seq-preload-circle seq-preload-circle-3" d="M31.322 15.334c4.049 0 7.332-3.282 7.332-7.332 0-4.049-3.282-7.332-7.332-7.332s-7.332 3.283-7.332 7.332c0 4.05 3.283 7.332 7.332 7.332z"/></g></svg>
      </div>

    </div>


        <nav>
          <div class="logo">
            <img src="{% static 'img/logo.png'%}" alt="">
          </div>
          <div class="mini-logo">
              <img src="{% static 'img/mini_logo.png' %}" alt="">
          </div>
          <ul>
            <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> <em>Home</em></a></li>
            <li><a href="{% url 'members:login' %}"><i class="fa fa-user"></i> <em>Login</em></a></li>
          </ul>
        </nav>

        <div class="slides">
          <div class="slide">
            {% block content %}
            {% endblock %}
          </div>
        </div>

        <div class="footer">
            {% include 'base/footer.html' %}
        </div>


    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>

</body>
</html>

templates/base/footer.html
<div class="content">
    <p>Copyright &copy; 2020 MSI Shafik . <a href="http://www.facebook.com/shafik.te/">On Facebook</a> - <a href="https://www.linkedin.com/in/shafikte/" target="_parent">On LinkedIn</a></p>
</div>