itea/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name="home/home.html"), name='home'),
    path('members/', include('members.urls', namespace='members')),
    path('balance/', include('balance.urls', namespace='balance')),
    path('notice/', include('notice.urls', namespace='notice')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path

from notice.views import NoticeCreate, NoticeListView, NoticeDetailView, \
    NoticeUpdateView, NoticeDeleteView, NoticeBoard

app_name = "notice"

urlpatterns = [
    path('list/', NoticeListView.as_view(), name='notice-list'),
    path('create/', NoticeCreate.as_view(), name='notice-create'),
    path('<int:pk>/', NoticeDetailView.as_view(), name='notice-details'),
    path('<int:pk>/update/', NoticeUpdateView.as_view(), name='notice-edit'),
    path('<int:pk>/delete/', NoticeDeleteView.as_view(), name='notice-delete'),
    path('board/', NoticeBoard.as_view(), name='notice-board'),
]

notice/models.py
from django.db import models

from members.models import User


class Notice(models.Model):
    """
        Storing Notice Objects
    """
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notice')
    notice_title = models.CharField(max_length=255)
    notice_body = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ['-published_date']

notice/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
# specific to this view
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from notice.models import Notice
from applibs.permission import ExecutivePermissionMixin, OwnNoticePermissionMixin


class NoticeCreate(ExecutivePermissionMixin, CreateView):
    """
        Create Notice
    """
    template_name = 'notice/notice_create.html'
    model = Notice
    fields = ("notice_title", "notice_body")

    def get_success_url(self):
        return reverse_lazy('notice:notice-details', kwargs={'pk': self.object.id})

    def form_valid(self, form):
        f = form.save(commit=False)
        f.author = self.request.user
        f.save()
        return super().form_valid(form)


class NoticeListView(LoginRequiredMixin, ListView):
    """
    Show all notice list
    """
    model = Notice
    template_name = 'notice/notice_list.html'
    context_object_name = 'notices'

    def get_queryset(self, *args, **kwargs):
        object_list = Notice.objects.filter(status=True)
        paginator = Paginator(object_list, 20)  # maping total object with this paginator
        page = self.request.GET.get('page')  # getting current page number
        try:
            notices = paginator.page(page)
        except PageNotAnInteger:
            # if page is not an interger deliver first page
            notices = paginator.page(1)
        except EmptyPage:
            # if page is out of range deliver last page
            notices = paginator.page(paginator.num_pages)
        return notices


class NoticeDetailView(LoginRequiredMixin, DetailView):
    """
    Details of Notice
    """
    model = Notice
    template_name = 'notice/notice_details.html'
    context_object_name = 'notice'


class NoticeUpdateView(OwnNoticePermissionMixin, UpdateView):
    """
    Update Notice
    """

    model = Notice
    template_name = 'notice/notice_update.html'
    context_object_name = 'user'
    fields = ('notice_title', 'notice_body',)

    def get_success_url(self):
        return reverse_lazy('notice:notice-details', kwargs={'pk': self.object.id})


class NoticeDeleteView(OwnNoticePermissionMixin, DeleteView):
    """
    Delete transaction
    """
    model = Notice
    template_name = 'notice/notice_delete.html'
    context_object_name = 'notice'
    success_url = reverse_lazy('notice:notice-list')

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.status = False
        self.object.save()
        return HttpResponseRedirect(success_url)


class NoticeBoard(LoginRequiredMixin, View):

    def get(self, request):
        try:
            notice = Notice.objects.filter(status=True).latest('id')
        except:
            notice = None
        return render(request, 'notice/notice_board.html', {'notice': notice})

templates/notice/notice_board.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% load grouptags %}

{% block title %}Notice Board{% endblock %}

{% block content %}
<div class="content first-content ">
  <div class="container-fluid">
      <div class="col-md-12 bottom">
      {% if notice %}
         <h2>{{ notice.notice_title }}</h2>
          <p>Published By- {{ notice.author.name }}, Published Date: {{ notice.published_date }}</p>
          <p><em>{{ notice.notice_body }}</em></p>
          {% if request.user.id == notice.author.id %}
          <div class="fb-btn"><a href="{% url 'notice:notice-edit' notice.id %}">Edit</a></div>
          <div class="fb-btn"><a href="{% url 'notice:notice-delete' notice.id %}">Delete</a></div>
          {% endif %}
          <br><br>
          <div class="fb-btn"><a href="{% url 'notice:notice-list' %}">See All Notice</a></div>
       {% else %}
            <h2>No notice published yet...!</h2>
      {% endif %}
      {% if request.user|has_group:"Executive"%}
      <div class="fb-btn" id="bottom"><a href="{% url 'notice:notice-create'%}">Publish New Notice</a></div>
      {% endif %}
      </div>
  </div>
</div>{% endblock %}

templates/notice/notice_create.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block title %}Publish New Notice{% endblock %}

{% block content %}
<div class="content first-content">
  <div class="container-fluid">
      <div class="col-md-9 bottom">
          <h2>Publish New Notice</h2>
          <form method="post">
            {% csrf_token %}
              {% for field in form %}
              <div class="form-group" >
                {{field.errors}}
                {{field.label_tag}}
                {% render_field field class="form-control" %}
              </div>
              {% endfor %}
              <button class="btn btn-primary" type="submit">Publish</button>
          </form>

      </div>
  </div>
</div>

{% endblock %}

templates/notice/notice_delete.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block title %}Delete Notice{% endblock %}

{% block content %}
<div class="content first-content">
  <div class="container-fluid">
      <div class="col-md-9 bottom">
          <h2>Delete Notice</h2>
          <form method="post">
            {% csrf_token %}
              {% for field in form %}
              <div class="form-group" >
                {{field.errors}}
                {{field.label_tag}}
                {% render_field field class="form-control" %}
              </div>
              {% endfor %}
              <button class="btn btn-primary" type="submit">Delete</button>
          </form>

      </div>
  </div>
</div>

{% endblock %}

templates/notice/notice_details.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Notice Details{% endblock %}

{% block content %}
<div class="content first-content">
  <div class="container-fluid">
      <div class="col-md-12 bottom">
          <h2>{{ notice.notice_title }}</h2>
          <p>Published By- {{ notice.author.name }}, Published Date: {{ notice.published_date }}</p>
          <p><em>{{ notice.notice_body }}</em></p>
          {% if request.user.id == notice.author.id %}
          <div class="fb-btn"><a href="{% url 'notice:notice-edit' notice.id %}">Edit</a></div>
          <div class="fb-btn"><a href="{% url 'notice:notice-delete' notice.id %}">Delete</a></div>
          {% endif %}

      </div>
  </div>
</div>{% endblock %}

templates/notice/notice_list.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load grouptags %}


{% block title %}Notice List{% endblock %}

{% block content %}
<div class="content fourth-content">
    <div class="container-fluid">
        <div class="col-md-12 bottom">
            <div class="left-content">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i> <h2 id="head-text">Notice Lists:</h2>
                </div>
                <div class="card-block">
                    <table class="table table-bordered table-striped table-sm text-center">
                        <thead>
                        <tr>
                            <th> <h3 class="text-center" id="text"> Date</h3> </th>
                            <th> <h3 class="text-center" id="text"> Title</h3> </th>
                            <th> <h3 class="text-center" id="text"> Publisher</h3> </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for notice in notices %}
                        <tr>
                            <td><a href="#" class="test-success"><span class="btn text-dark" id="table-text">{{ notice.published_date }}</span></a></td>
                            <td><a href="{% url 'notice:notice-details' notice.id %}" class="test-success"><span class="btn text-dark" id="table-text">{{ notice.notice_title }}</span></a></td>
                            <td><a href="#" class="test-success"><span class="btn text-dark" id="table-text">{{ notice.author }}</span></a></td>
                        </tr>
                        {% endfor %}
                        </tbody>

                    </table>
                    {% include "pagination/pagination.html" with page=notices %}
                </div>
          </div>
        </div>
    </div>
</div>
{% endblock %}

templates/notice/notice_update.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block title %}Notice Update Form{% endblock %}

{% block content %}
<div class="content first-content">
  <div class="container-fluid">
      <div class="col-md-9 bottom">
          <h2>Update Form</h2>
          <form method="post">
            {% csrf_token %}
              {% for field in form %}
              <div class="form-group" >
                {{field.errors}}
                {{field.label_tag}}
                {% render_field field class="form-control" %}
              </div>
              {% endfor %}
              <button class="btn btn-primary" type="submit">Update</button>
          </form>

      </div>
  </div>
</div>

{% endblock %}